export const SET_ALERT = "SET_ALERT";
export const REMOVE_ALERT = "REMOVE_ALERT";

export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const LOGOUT = "LOGOUT";

export const SCRAPE_SUCCESS = "SCRAPE_SUCCESS";
export const SCRAPE_FAIL = "SCRAPE_FAIL";
export const FETCH_SCRAPED_DATA_SUCCESS = "FETCH_SCRAPED_DATA_SUCCESS";
export const FETCH_SCRAPED_DATA_FAIL = "FETCH_SCRAPED_DATA_FAIL";
